version: '3'

services:

  graphdb:
    image: "numbleroot/neo4j-apoc:3.3.3"
    build: "./"
    container_name: "graphdb"
    hostname: "graphdb"
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    volumes:
      - "./tmp:/data"
    environment:
      - "NEO4J_AUTH=none"
      - "NEO4J_dbms_memory_pagecache_size=8192m"
      - "NEO4J_dbms_memory_heap_max__size=8192m"
      - "NEO4J_dbms_memory_heap_initial__size=8192m"
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*"
      - "NEO4J_apoc_export_file_enabled=true"
      - "NEO4J_apoc_import_file_enabled=true"
    network_mode: "bridge"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
